name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload Mobile App Debug STD APK
        uses: actions/upload-artifact@v1
        with:
          name: mobileapp
          path: mobileapp/build/outputs/apk/std/debug/mobileapp-std-debug.apk
      - name: Upload Mobile App Release STD APK
        uses: actions/upload-artifact@v1
        with:
          name: mobileapp
          path: mobileapp/build/outputs/apk/std/release/mobileapp-std-release.apk
      - name: Upload TV App Debug STD APK
        uses: actions/upload-artifact@v1
        with:
          name: tvapp
          path: tvapp/build/outputs/apk/std/debug/tvapp-std-debug.apk
      - name: Upload TV App Release STD APK
        uses: actions/upload-artifact@v1
        with:
          name: tvapp
          path: tvapp/build/outputs/apk/std/release/tvapp-std-release.apk