name: Android CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    name: Generate APKs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Mobile App STD APKs
      uses: actions/upload-artifact@v1
      with:
        name: mobileapp-std
        path: mobileapp/build/outputs/apk/std
    - name: Upload TV App STD APK
      uses: actions/upload-artifact@v1
      with:
        name: tvapp-std
        path: tvapp/build/outputs/apk/std

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: ./gradlew check
      - name: Upload unit tests reports
        uses: actions/upload-artifact@v1
        with:
          name: unit-test-report
          path: iptvservicecommunicator/build/reports/tests

  instrumentedtest:
    name: Run instrumented tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2.13.0
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
      - name: Upload Reports for IPTV service instrumented tests
        uses: actions/upload-artifact@v1
        with:
          name: iptvservice-instrumented-test
          path: iptvservicecommunicator/build/reports/androidTests/connected/flavors